# Generated by Django 5.0.2 on 2024-11-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='department',
            field=models.CharField(default='Unassigned', max_length=20),
            preserve_default=False,
        ),
    ]
