# Generated by Django 5.0.2 on 2024-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_appointments_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
